-- Integration fixture: everything, including auth users, is rolled back.
begin;
create temporary table idle_test_results(test text);
do $$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid(); asset uuid; lid uuid; lid2 uuid; r jsonb; req uuid; p jsonb; gold_before bigint; sum_before numeric;
begin
 select coalesce(sum(gold),0) into sum_before from public.players;
 insert into auth.users(id,email) values(a,'idle-test-'||a||'@example.invalid'),(b,'idle-test-'||b||'@example.invalid'),(c,'idle-test-'||c||'@example.invalid');
 perform public.idle_commerce(a,'state','{}',null);perform public.idle_commerce(b,'state','{}',null);perform public.idle_commerce(c,'state','{}',null);
 assert (select gold=0 from public.idle_accounts where user_id=a),'new account must not import or mint currency';
 update public.idle_accounts set gold=1000 where user_id in(a,b,c);
 insert into public.idle_assets(owner_id,kind,category,name,quantity) values(a,'item','stone','Fire Stone',10) returning id into asset;
 req:=gen_random_uuid();p:=jsonb_build_object('asset_id',asset,'asset_kind','item','kind','market','quantity',3,'price',100,'hours',24,'currency','gold');
 r:=public.idle_commerce(a,'create',p,req);lid:=(r->>'listing_id')::uuid;
 assert (select quantity=7 from public.idle_assets where id=asset),'escrow removes only requested quantity';
 assert public.idle_commerce(a,'create',p,req)=r,'duplicate create returns receipt';
 assert (select count(*)=1 from public.idle_listings where seller_id=a),'duplicate create must not create a second listing';
 insert into idle_test_results values('partial escrow + idempotent creation');
 begin perform public.idle_commerce(a,'buy',jsonb_build_object('listing_id',lid),gen_random_uuid());raise exception 'TEST own purchase accepted';exception when others then if sqlerrm<>'own_listing' then raise;end if;end;
 req:=gen_random_uuid();p:=jsonb_build_object('listing_id',lid);perform public.idle_commerce(b,'buy',p,req);perform public.idle_commerce(b,'buy',p,req);
 assert (select gold=900 from public.idle_accounts where user_id=b),'buyer debited exactly once';
 assert (select gold=1100 from public.idle_accounts where user_id=a),'seller credited once';
 assert (select sum(quantity)=3 from public.idle_assets where owner_id=b and name='Fire Stone'),'buyer receives lot once';
 begin perform public.idle_commerce(c,'buy',p,gen_random_uuid());raise exception 'TEST second purchase accepted';exception when others then if sqlerrm<>'listing_unavailable' then raise;end if;end;
 insert into idle_test_results values('purchase + retry + second buyer + own listing protection');
 insert into public.idle_assets(owner_id,kind,category,name,quantity,bound) values(a,'item','egg','Bound Egg',1,true) returning id into asset;
 begin perform public.idle_commerce(a,'create',jsonb_build_object('asset_id',asset,'kind','market','quantity',1,'price',1,'hours',24,'currency','gold'),gen_random_uuid());raise exception 'TEST bound item accepted';exception when others then if sqlerrm<>'asset_unavailable_or_bound' then raise;end if;end;
 update public.idle_accounts set psycoin=10,bound_psycoin=10 where user_id=a;
 begin perform public.idle_commerce(a,'create','{"asset_kind":"psycoin","kind":"market","quantity":1,"price":1,"hours":24,"currency":"gold"}',gen_random_uuid());raise exception 'TEST bound coin accepted';exception when others then if sqlerrm<>'insufficient_balance' then raise;end if;end;
 insert into idle_test_results values('bound items and bound PsyCoin rejected');
 insert into public.idle_assets(owner_id,kind,category,name,quantity) values(a,'item','profession','Ruby',2) returning id into asset;
 r:=public.idle_commerce(a,'create',jsonb_build_object('asset_id',asset,'kind','auction','quantity',1,'price',50,'buyout',100,'hours',6,'currency','gold'),gen_random_uuid());lid:=(r->>'listing_id')::uuid;
 perform public.idle_commerce(b,'bid',jsonb_build_object('listing_id',lid,'amount',60),gen_random_uuid());
 assert (select gold=840 from public.idle_accounts where user_id=b),'bid escrow';
 perform public.idle_commerce(c,'bid',jsonb_build_object('listing_id',lid,'amount',80),gen_random_uuid());
 assert (select gold=900 from public.idle_accounts where user_id=b),'outbid refund';
 begin perform public.idle_commerce(a,'cancel',jsonb_build_object('listing_id',lid),gen_random_uuid());raise exception 'TEST bid auction cancelled';exception when others then if sqlerrm<>'auction_has_bids' then raise;end if;end;
 begin perform public.idle_commerce(b,'bid',jsonb_build_object('listing_id',lid,'amount',79),gen_random_uuid());raise exception 'TEST lower bid accepted';exception when others then if sqlerrm<>'bid_too_low' then raise;end if;end;
 perform public.idle_commerce(b,'bid',jsonb_build_object('listing_id',lid,'amount',101),gen_random_uuid());
 assert (select gold=1000 from public.idle_accounts where user_id=c),'buyout refunds prior bidder';
 assert (select gold=800 from public.idle_accounts where user_id=b),'buyout uses cap price';
 assert (select status='sold' and buyer_id=b from public.idle_listings where id=lid),'buyout settlement';
 assert (select count(*)=3 from public.idle_bid_history where listing_id=lid),'all accepted bids retained';
 r:=public.idle_browse_commerce(c,'auction','history','all','',0);
 assert (r->>'count')::int=1,'outbid buyer sees finished auction in history';
 assert not ((r->'list'->0)?'seller_id'),'catalog does not expose account IDs';
 insert into idle_test_results values('bid reserve + outbid refund + cancel rejection + buyout');
 r:=public.idle_commerce(a,'create',jsonb_build_object('asset_id',asset,'kind','auction','quantity',1,'price',25,'hours',6,'currency','gold'),gen_random_uuid());lid:=(r->>'listing_id')::uuid;
 perform public.idle_commerce(c,'bid',jsonb_build_object('listing_id',lid,'amount',30),gen_random_uuid());
 update public.idle_listings set expires_at=now()-interval '1 second' where id=lid;
 perform public.idle_expire_commerce();
 assert (select status='sold' and buyer_id=c from public.idle_listings where id=lid),'expired auction awards winner without seller online';
 assert (select gold=970 from public.idle_accounts where user_id=c),'winner not charged twice';
 insert into idle_test_results values('scheduled expiry settlement without connected players');
 insert into public.idle_assets(owner_id,kind,category,name,quantity) values(a,'item','egg','Mystery Egg',2) returning id into asset;
 r:=public.idle_commerce(a,'create',jsonb_build_object('asset_id',asset,'kind','market','quantity',1,'price',100,'hours',6,'currency','gold'),gen_random_uuid());lid:=(r->>'listing_id')::uuid;
 perform public.idle_commerce(a,'cancel',jsonb_build_object('listing_id',lid),gen_random_uuid());
 assert (select sum(quantity)=2 from public.idle_assets where owner_id=a and name='Mystery Egg'),'cancellation returns lot';
 r:=public.idle_commerce(a,'create',jsonb_build_object('asset_id',asset,'kind','market','quantity',1,'price',100,'hours',6,'currency','gold'),gen_random_uuid());lid:=(r->>'listing_id')::uuid;
 update public.idle_listings set expires_at=now()-interval '1 second' where id=lid;
 perform public.idle_commerce(a,'state','{}',null);
 assert (select status='expired' from public.idle_listings where id=lid),'expiry without buyer';
 assert (select sum(quantity)=2 from public.idle_assets where owner_id=a and name='Mystery Egg'),'expiry returns lot';
 insert into idle_test_results values('cancel and unbid expiry restore assets');
 -- A backlog beyond the scheduled batch must never make a late purchase valid.
 insert into public.idle_listings(seller_id,kind,category,name,quantity,asset_kind,currency,price,expires_at)
 select a,'market','item','Expired fixture',1,'item','gold',1,now()-interval '2 days' from generate_series(1,101);
 insert into public.idle_listings(seller_id,kind,category,name,quantity,asset_kind,currency,price,expires_at)
 values(a,'auction','item','Last expired fixture',1,'item','gold',1,now()-interval '1 day') returning id into lid2;
 begin perform public.idle_commerce(b,'bid',jsonb_build_object('listing_id',lid2,'amount',10),gen_random_uuid());raise exception 'TEST late bid accepted';exception when others then if sqlerrm<>'listing_unavailable' then raise;end if;end;
 begin perform public.idle_commerce(b,'buy',jsonb_build_object('listing_id',lid2),gen_random_uuid());raise exception 'TEST late buy accepted';exception when others then if sqlerrm<>'listing_unavailable' then raise;end if;end;
 insert into idle_test_results values('expired target rejected even beyond expiry batch');
 assert (select coalesce(sum(gold),0)=sum_before from public.players),'PSYWORLD wallet untouched';
 assert not has_function_privilege('authenticated','public.idle_commerce(uuid,text,jsonb,uuid)','EXECUTE'),'client cannot impersonate user';
 assert not has_table_privilege('authenticated','public.idle_accounts','UPDATE'),'client cannot mint balances';
 assert (select bool_and(relrowsecurity) from pg_class where oid in ('public.idle_accounts'::regclass,'public.idle_assets'::regclass,'public.idle_listings'::regclass)),'RLS enabled';
 insert into idle_test_results values('PSYWORLD isolation + RPC grants + RLS');
end $$;
select * from idle_test_results;
rollback;
